### PR TITLE
Fancy.

### PR DESCRIPTION
**Pull request by Kyousei**

### CODE REVIEW

**Comment by Deivedux** [comment]
I'm afraid of merging this... How will it look like in action?

**Comment by Kyousei** [comment]
Just DO IT! You won't regret it. :smile:

**Comment by Deivedux** [comment]
Wow, that's fancy 😄

**Comment by Kyousei** [comment]
Oh and, I made it. :GWchadThink:

**Comment by Deivedux** [comment]
It's a bit poor quality, but whatever 😄

**Comment by Kyousei** [comment]
oh shut up you. :think:
I already have a guy complaining about a tiny pixel

**Comment by Kyousei** [comment]
add dlbot

**Comment by Kyousei** [comment]
Foken updated.

**Pull request merged**
